Neos:
  Form:
    presets:
      default:
        finisherPresets:
          'SimpleSolution.MailerLiteFinisher:MailerLiteFinisher':
            implementationClassName: SimpleSolution\MailerLiteFinisher\Finishers\MailerLiteFinisher